# .travis.yml
language: "go"

dist: "xenial"

os:
  - "linux"
go:
  - "1.14.x"

script:
  - go test test/main.go test/main_test.go -v
  - go test test/main.go test/cheader_test.go -v
  - go vet cmd/main.go
  - go build cmd/main.go
  - sh build_all_plugins.sh