ListenPort = 8081
DefaultTarget = "0.0.0.0:8080"
PPROFPort = 8999
LogFlag = "ltd"
Middleware = "sub_filter,c_header,stdout,js_lua"
Mode = "blend"
LuaPath="./middlewares/js_lua/sub_custom.lua"
JsPath="./middlewares/js_lua/sub_custom.js"

# pass_proxy work on blend and proxy mode
[ProxyUrls]
    [ProxyUrls.test]
    Scheme="http"
    Host="0.0.0.0:8989"
    Path="/statics/*"

# c_header config
[CustomHeaders]
    [CustomHeaders.req1]
    Key="X-REAL-IP"
    Value="111.111.111.111"

    [CustomHeaders.resp1]
    Key="Server"
    Value="ASP.NET"

# sub_filter config
[SubFilter]
    [SubFilter.test]
    Old="</head>"
    Repl='<script src="/js/jquery.min.js"></script></head>'
    Path="/"