name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up GO 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Go vet
        run: go vet cmd/main.go

      - name: Go Build
        run: go build -o superlcx cmd/main.go

      - name: Go Build Without Middleware
        run: go build -tags plugin -o superlcx cmd/main.go

      - name: Go All Plugins
        run: sh build_all_plugins.sh