name: auto_release

on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up GO 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Go Build
        run: |
          make build GOOS=linux ARCH=amd64 TARGET=superlcx_linux_amd64;  \
          make build GOOS=darwin arch=amd64 TARGET=superlcx_darwin_amd64; \
          make build GOOS=windows arch=amd64 TARGET=superlcx_windows_amd64.exe;

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Archive linux_amd64
        uses: thedoctor0/zip-release@master
        with:
          path: superlcx_linux_amd64
          filename: '${{steps.tag.outputs.tag}}_linux_amd64.zip'

      - name: Archive darwin_amd64
        uses: thedoctor0/zip-release@master
        with:
          path: superlcx_darwin_amd64
          filename: '${{steps.tag.outputs.tag}}_darwin_amd64.zip'

      - name: Archive windows_amd64
        uses: thedoctor0/zip-release@master
        with:
          path: superlcx_windows_amd64.exe
          filename: '${{steps.tag.outputs.tag}}_windows_amd64.zip'

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          body_path: FEATURES.txt
          files: |
            ${{steps.tag.outputs.tag}}_linux_amd64.zip
            ${{steps.tag.outputs.tag}}_darwin_amd64.zip
            ${{steps.tag.outputs.tag}}_windows_amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}